### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by isyzwang** [StitchKoala/STLM#2]
你好，我在运行trainSTLM.py文件时，报错ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [] and output size of torch.Size([256, 256]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

**Comment by WangJunjie97** [comment]
hi

**Comment by flyingtiger111** [comment]
> 你好，我在运行trainSTLM.py文件时，报错ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [] and output size of torch.Size([256, 256]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

你解决了这个问题了吗？我复现的时候，遇到了同样的报错

**Comment by ctj1007** [comment]
Have you solved it? I had the same problem

**Comment by StitchKoala** [comment]
你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传
![image](https://github.com/StitchKoala/STLM/assets/150821565/c51d56b1-4f60-4453-a148-5bb4735d9b6c)

**Comment by flyingtiger111** [comment]
> 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)

是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数
required keyword-only arguments: 'transformer_dim' and 'transformer'

**Comment by ctj1007** [comment]
> 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![图像](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MDg2MDcsIm5iZiI6MTcxNzgwODMwNywicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwMDU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDIxNWExN2QzZjg5MmQzZDgzMDcxZDEwNDZhZWQ4YzZjNDg2Nzk2ODYyZDRkMzk0MzQzYzU5YTk2NmNjZDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AvKwunvwqZzvDTAcUpAWtSidnwFVMbbtxT37-4vXoK4)
Thanks for your reply

**Comment by wu33learn** [comment]
> > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> 
> 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'

请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling
这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。

**Comment by flyingtiger111** [comment]
> > > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> > 
> > 
> > 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'
> 
> 请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling 这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。

程序能跑通。就是时间很长。

**Comment by wu33learn** [comment]
> > > > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> > > 
> > > 
> > > 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'
> > 
> > 
> > 请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling 这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。
> 
> 程序能跑通。就是时间很长。

请问你用啥配置跑的啊，我这个正常吗，跑三个小时了，capsule没动过了，看gpu是都在运行

**Comment by wu33learn** [comment]
> > > > > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> > > > 
> > > > 
> > > > 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'
> > > 
> > > 
> > > 请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling 这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。
> > 
> > 
> > 程序能跑通。就是时间很长。
> 
> 请问你用啥配置跑的啊，我这个正常吗，跑三个小时了，capsule没动过了，看gpu是都在运行

请问我这样安装mobile sam正确吗

**Comment by flyingtiger111** [comment]
> > > > > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> > > > 
> > > > 
> > > > 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'
> > > 
> > > 
> > > 请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling 这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。
> > 
> > 
> > 程序能跑通。就是时间很长。
> 
> 请问你用啥配置跑的啊，我这个正常吗，跑三个小时了，capsule没动过了，看gpu是都在运行

同3090 。我记得一个类跑了好长时间（单位是天），后来我就放弃了

**Comment by wu33learn** [comment]
> > > > > > 你好，需要修改mask_decoder，返回decoder中间的两个feature，文件已上传 ![image](https://private-user-images.githubusercontent.com/150821565/337585767-c51d56b1-4f60-4453-a148-5bb4735d9b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzMxNDEsIm5iZiI6MTcxNzc3Mjg0MSwicGF0aCI6Ii8xNTA4MjE1NjUvMzM3NTg1NzY3LWM1MWQ1NmIxLTRmNjAtNDQ1My1hMTQ4LTViYjQ3MzVkOWI2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmM1ODdmN2E3ZWEwZjQ2NmM1MGU2NDc1M2I2YTk5NmFhOTFjYjQxMmJiMmMzOWJjZjlmYmZkNWY5Zjc4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GiXYCpi-JmvUqLmONUWfpmdjQsMdCb1WPMuOgbAVAA)
> > > > > 
> > > > > 
> > > > > 是不是要将mob_sam.py中的self.model.mask_decoder修改成您提供的mask_decoder? 似乎需要两个关键参数 required keyword-only arguments: 'transformer_dim' and 'transformer'
> > > > 
> > > > 
> > > > 请问你运行出来了吗，我把https://github.com/ChaoningZhang/MobileSAM/tree/master/mobile_sam/modeling 这个文件夹下的mask_decoder替换了，现在用3090跑，差不多3小时了，capsule还没跑完。
> > > 
> > > 
> > > 程序能跑通。就是时间很长。
> > 
> > 
> > 请问你用啥配置跑的啊，我这个正常吗，跑三个小时了，capsule没动过了，看gpu是都在运行
> 
> 同3090 。我记得一个类跑了好长时间（单位是天），后来我就放弃了

我滴妈啊，那么长，算了不弄了，谢谢啊，不然我都不知道呢，感谢噢
